accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'
urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='article')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    create_at = models.DateField(auto_created=True, null=True)

templates/snippets/card.html
<img src="{{ article.image.url }}">

templates/snippets/card_project.html
<div style="display: block; text-align: center">
    <img src="{{ project.image.url }}">
    <h5 class="mt-2">
        {{ project.title | truncatechars:8 }}
    </h5>

</div>

templates/snippets/list_fragment.html
{% load static %}

<style>
    .container{
        padding: 0;
        margin: 0 auto;
    }

    .container a{
        width: 45%;
        max-width: 250px;
    }

    .container div {
      width: 250px;
      background-color: antiquewhite;
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 3rem;
    }
    .container img{
        width: 100%;
        border-radius: 3rem;
    }
</style>
    {% if article_list %}
        <div class="container">
            {% for article in article_list %}

                <a href="{% url 'articleapp:detail' pk=article.pk %}">
                    {% include 'snippets/card.html' with article=article %}
                </a>
            {% endfor %}
        </div>
        <script src="{% static 'js/magicgrid.js' %}"></script>

    {% else %}
        <div style="text-align: center;">
            <h1>No Articles YET~~~~~~~</h1>
        </div>
    {% endif %}

    {% include 'snippets/pagination.html' with page_obj=page_obj %}
    <div style="text-align: center">
        <a href="{% url 'articleapp:create' %}" class="btn btn-primary rounded-pill col-3 mt-3 mb-3 ㅔㅌ-2">
                Create Article
        </a>
    </div>

templates/snippets/pagination.html
<div style="text-align: center; margin: 1rem 0;">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}"
           class="btn btn-secondary rounded-pill">
            {{ page_obj.previous_page_number }}
        </a>
    {% endif %}
        <a href="?page={{ page_obj.number }}"
           class="btn btn-secondary rounded-pill active">
            {{ page_obj.number }}
        </a>
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"
           class="btn btn-secondary rounded-pill">
            {{ page_obj.next_page_number }}
        </a>
    {% endif %}


</div>