accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'
urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

articleapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='article')
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='article')

    title = models.CharField(max_length=200, null=True)
    image = models.ImageField(upload_to='article/', null=False)
    content = models.TextField(null=True)

    create_at = models.DateField(auto_created=True, null=True)

projectapp/models.py
from django.db import models

# Create your models here.


class Project(models.Model):
    title = models.CharField(max_length=30, null=False)
    description = models.CharField(max_length=255, null=True)
    image = models.ImageField(upload_to='project/', null=False)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.pk} : {self.title}'

projectapp/forms.py
from django.forms import ModelForm

from projectapp.models import Project


class ProjectCreationForm(ModelForm):
    class Meta:
        model = Project
        fields = ['image', 'title', 'description']

projectapp/views.py
from django.shortcuts import render

# Create your views here.
from django.urls import reverse
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.list import MultipleObjectMixin

from articleapp.models import Article
from projectapp.forms import ProjectCreationForm
from projectapp.models import Project
from subscribeapp.models import Subscription


class ProjectCreateView(CreateView):
    model = Project
    context_object_name = 'target_project'
    form_class = ProjectCreationForm
    template_name = 'projectapp/create.html'

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.object.pk})


class ProjectDetailView(DetailView, MultipleObjectMixin):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/detail.html'

    def get_context_data(self, **kwargs):
        project = self.object
        user = self.request.user

        if user.is_authenticated:
            subscription = Subscription.objects.filter(user=user, project=project)
        else:
            subscription = None

        object_list = Article.objects.filter(project=self.get_object())
        return super(ProjectDetailView, self).get_context_data(object_list=object_list, subscription=subscription, **kwargs)


    paginate_by = 5


class ProjectListView(ListView):
    model = Project
    context_object_name = 'target_project'
    template_name = 'projectapp/list.html'
    paginate_by = 5

projectapp/templates/projectapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-5">
        <h4>Proejct Create</h4>
    </div>
        <form action="{% url 'projectapp:create' %}" method="post", enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary rounded-pill">
        </form>
    </div>
{% endblock %}

projectapp/templates/projectapp/detail.html
{% extends 'base.html' %}

{% block content %}
    <div style="text-align: center; max-width: 700px; margin: 4rem auto;">
        <div>
            <h2>
                Title = {{ target_project.title }}
            </h2>
        </div>
        <div>
            <img src="{{ target_project.image.url }}">
        </div>
        <div>
            <h5>
                Desc = {{ target_project.description }}
            </h5>
        </div>
        <div>
            {% if user.is_authenticated %}
                {% if not subscription %}
                    <a href="{% url 'subscribeapp:subscribe'%}?project_pk={{ target_project.pk }}" class="btn btn-primary">
                        Subscribe
                    </a>
                {% else %}
                       <a href="{% url 'subscribeapp:subscribe'%}?project_pk={{ target_project.pk }}" class="btn btn-danger">
                        Unsubscribe
                    </a>
                {% endif %}
            {% endif %}
        </div>
    </div>
    <div>
            {% include 'snippets/list_fragment.html' with article_list=object_list %}
    </div>
{% endblock %}

projectapp/templates/projectapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<style>
    .container{
        padding: 0;
        margin: 0 auto;
    }

    .container div {
      display: flex;
      justify-content: center;
      align-items: center;
      border-radius: 1rem;
    }
    .container img{
        width: 7rem;
        height: 7rem;
        object-fit: cover;
        border-radius: 3rem;
    }
</style>
        <div class="container">
            {% for project in target_project %}
                <a href="{% url 'projectapp:detail' pk=project.pk %}" style="object-fit: cover;">
                    {% include 'snippets/card_project.html' with project=project%}
                </a>
            {% endfor %}
        </div>
        <script src="{% static 'js/magicgrid.js' %}"></script>

        {% include 'snippets/pagination.html' with page_obj=page_obj %}
{% endblock %}