accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include

from accountapp.views import  AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('create/', AccountCreateView.as_view(), name='create'),
    path('detail/<int:pk>', AccountDetailView.as_view(), name='detail'),
    path('update/<int:pk>', AccountUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name='delete'),

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

articleapp/urls.py
from django.urls import path
from django.views.generic import TemplateView

from articleapp.views import ArticleCreateView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView, ArticleListView

app_name = 'articleapp'
urlpatterns = [
    path('list/', ArticleListView.as_view(), name='list'),
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ArticleDetailView.as_view(), name='detail'),
    path('update/<int:pk>', ArticleUpdateView.as_view(), name='update'),
    path('delete/<int:pk>', ArticleDeleteView.as_view(), name='delete'),
]

projectapp/urls.py
from django.urls import path

from projectapp.views import ProjectCreateView, ProjectDetailView, ProjectListView

app_name = 'projectapp'

urlpatterns = [
    path('create/', ProjectCreateView.as_view(), name='create'),
    path('detail/<int:pk>', ProjectDetailView.as_view(), name='detail'),
    path('list/', ProjectListView.as_view(), name='list'),
]

subscribeapp/urls.py
from django.urls import path

from subscribeapp.views import SubscriptionView, SubscriptionListView

app_name = 'subscribeapp'
urlpatterns = [
    path('subscribe/', SubscriptionView.as_view(), name='subscribe'),
    path('list/', SubscriptionListView.as_view(), name='list'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">

{% include 'head.html' %}
<body>
    {% include 'header.html' %}

    <hr>

    {% block content %}
    {% endblock %}

    <hr>

    {% include 'footer.html' %}
</body>
</html>

templates/footer.html
    <div class="footer_div">
        <div class="footer_button">
            <span>이것</span> |
            <span>이것</span> |
            <span>저것</span> |
            <span>이것</span>
        </div>
        <div>
            <h6>고정근이 홈페이지</h6>
        </div>

    </div>

templates/head.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Title</title>
    {# BOOTSTRAP LINK   #}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet", type="text/css", href="{% static 'base.css' %}">
    {#    GOOGLE MATERIAL ICONS#}
    <link href="https://fonts.googleapis.com/css2?family=Material+Icons"
      rel="stylesheet">
</head>

templates/header.html
    <div class="header_div">
        <div>
            <a href="">
                <h1>고정근이 홈페이지</h1>
            </a>
        </div>
        <div class="ko_header_navbar">

            <a href="{% url 'articleapp:list' %}" class="ko_header_nav">
                <span>Articles</span>
            </a>
            <a href="{% url 'projectapp:list' %}" class="ko_header_nav">
                <span>Projects</span>
            </a>

            <a href="{% url 'subscribeapp:list' %}" class="ko_header_nav">
                <span>Subscriptions</span>
            </a>

{#        로그인이 돼있는지 체크 로그인이 안되어 있으면 로그인 창으로 이동#}
            {% if not user.is_authenticated %}
                <a href="{% url 'accountapp:create' %}" class="ko_header_nav">
                    <span>SignUp</span>
                </a>
                <a href="{% url 'accountapp:login' %}?next={{ request.path }}" class="ko_header_nav">
                    <span>login</span>
                </a>
            {% else %}
                <a href="{% url 'accountapp:detail' pk=user.pk %}" class="ko_header_nav">
                    <span>MyPage</span>
                </a>
                <a href="{% url 'accountapp:logout' %}?next={{ request.path }}" class="ko_header_nav">
                    <span>logout</span>
                </a>
            {% endif %}
        </div>
    </div>